# Exercice 1.11 du devoir 

Márcio Reverbel

In [11]:
import numpy as np
import numpy.linalg as la

In [12]:
# We use P to indicate the matrix of weights, as D already is used to 
# represent the matrix of distances.
I = np.identity(3)
P = 1/3*I
D = np.array([[0, 0, 0],[0, 0, 0],[0, 0, 0]])
ones = np.ones((3, 3))
D[0,1], D[1,2], D[1,0], D[2,1], D[0,2], D[2,0] = 1, 1, 1, 1, 2, 2

D

array([[0, 1, 2],
       [1, 0, 1],
       [2, 1, 0]])

In [13]:
W = -0.5*(D - P@ones@D - D@ones@P + P@ones@D@ones@P)
WP = W@P
WP

array([[ 0.18518519, -0.03703704, -0.14814815],
       [-0.03703704,  0.07407407, -0.03703704],
       [-0.14814815, -0.03703704,  0.18518519]])

In [14]:
eigenvalue, eigenvector = la.eig(WP)

print("The eigenvalues are: \n\n{}".format(eigenvalue))
print()
print("And their respective (unit) eigenvectors are: \n\n{}".format(eigenvector)) 

The eigenvalues are: 

[3.33333333e-01 9.24917627e-18 1.11111111e-01]

And their respective (unit) eigenvectors are: 

[[-7.07106781e-01  5.77350269e-01  4.08248290e-01]
 [ 1.90819582e-17  5.77350269e-01 -8.16496581e-01]
 [ 7.07106781e-01  5.77350269e-01  4.08248290e-01]]


In [15]:
# The eigenvectors are columns of the matrix. We make the following transformation 
# to make it easier to manipulate:
eigenvector = eigenvector.T

In [16]:
# Notice how the second vector is indeed [sqrt(Pi)], the scaled 'ones' vector 
# mentioned in exercise 1.9:

for i in range(3):
    print("||{}||² = {}\n".format(eigenvector[i], la.norm(eigenvector[i])))

||[-7.07106781e-01  1.90819582e-17  7.07106781e-01]||² = 1.0

||[0.57735027 0.57735027 0.57735027]||² = 1.0

||[ 0.40824829 -0.81649658  0.40824829]||² = 1.0



In [17]:
# Here we test that the calculations indeed make sense, 
# by testing WP*v = Lambda * v, the definition of eigenvectors and eigenvalues.

# (True => values are sufficiently close, considering float point approximations.)

for val, vec in zip(eigenvalue, eigenvector):
    print(np.isclose(WP@vec, val*vec)) 

[ True  True  True]
[ True  True  True]
[ True  True  True]


We can clean the eigenvalues and eigenvectors a little bit, since they're 
approximated calculations by the computer sometimes lead to unpractical 
representations (such as 1.90819582e-17, which is equal to 0).

In [21]:
eigenvalue[1] = 0
eigenvector[0][1] = 0

# Checking that the calculated eigenvectors are indeed unit vectors:

for i in range(3): 
    print(eigenvector[i]@eigenvector[i])

1.0
1.0000000000000002
1.0


In [22]:
# Here we transform the unit eigenvectors into f, the vector whose length is equal 
# to the eigenvector. Notice how the 2nd vector, [(1/sqrt(3))*unit vector] is taken 
# to zero to satisfy this condition (since it's eigenvalue is 0).

# (In case of the second vector, it naturally still makes sense to talk about 
# [0.57735027 0.57735027 0.57735027] as the eigenvector associated to Lambda_2 = 0).

f = np.empty([3, 3])
for i in range(3): 
    f[i] = eigenvector[i]*np.sqrt(eigenvalue[i])
    print("\nLambda_{} = {}, associated to f_{} = {}, \n".format(i+1, eigenvalue[i], i+1, f[i]))


Lambda_1 = 0.33333333333333315, associated to f_1 = [-0.40824829  0.          0.40824829], 


Lambda_2 = 0.0, associated to f_2 = [0. 0. 0.], 


Lambda_3 = 0.1111111111111111, associated to f_3 = [ 0.13608276 -0.27216553  0.13608276], 



In [23]:
# Here we observe that the length of f is indeed the lambda, proven in exercise 1.10.

for i in range(3): 
    print(f[i]@f[i])

0.33333333333333315
0.0
0.1111111111111111
